BraveBear/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orders</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BraveBear/force-app/main/default/objects/Order__c/fields/Final_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Amount__c</fullName>
    <description>Final amount after discount</description>
    <label>Final Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Manager Approval</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BraveBear/force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total_Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/fields/Quantity_Available__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quantity Available</label>
    <type>Checkbox</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <formula>Products__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BraveBear/force-app/main/default/objects/Products__c/Products__c.object-meta.xml
<CustomObject>
    <label>Products</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BraveBear/force-app/main/default/objects/Products__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

BraveBear/force-app/main/default/classes/OrderProcessingController.cls
public class OrderProcessingController {
    public static void process(Order__c order) {
        Account acc = [SELECT Tier__c FROM Account WHERE Id = :order.Account__c];
        Customer_Tiers__mdt	 getTierMetadata;
        String customerTierString= !string.isBlank(acc.Tier__c) ? acc.tier__c: 'Standard';
        boolean isInventoryQtyAvailable=true;
        
        getTierMetadata = Customer_Tiers__mdt.getInstance(customerTierString);        
        List<Order_Line_Item__c> lineItems = [SELECT Quantity__c,Products__c,products__r.ProductCode__c	,unit_price__c FROM Order_Line_Item__c WHERE Order__c = :order.Id];//
        Decimal total = 0;
        Decimal totalWithoutDiscount = 0;
        for (Order_Line_Item__c item : lineItems) {
            Decimal discount =   getTierMetadata.Discount__c;
            if (item.Quantity__c > 100) {
                discount += 2;
            }
            Decimal price = item.Quantity__c * item.unit_price__c * (1 - discount / 100);
            Decimal PriceWithoutDiscount=item.Quantity__c * item.unit_price__c;
            item.Discount__c = discount;
            item.Final_Amount__c = price;
            totalWithoutDiscount+=PriceWithoutDiscount;
            total += price;
            system.debug('Total Amount '+total);
            try {
                //  Boolean isInventoryAvailable = true;
                Boolean isInventoryAvailable = checkInventoryAvailability(item.products__r.ProductCode__c, item.Quantity__c);
                item.Quantity_Available__c=isInventoryAvailable;
                
                if (!isInventoryAvailable) {
                    isInventoryQtyAvailable = false;
                }
            } catch (Exception ex) {
                item.API_Response__c=ex.getMessage();
                isInventoryQtyAvailable = false;
                System.debug('Inventory API call failed: ' + ex.getMessage());
            }
        }
        update lineItems;
        
        order.Total_Amount__c = total;
        order.Discount__c =   !string.isBlank(acc.Tier__c) ? getTierMetadata.Discount__c: 0.0;
        order.Final_Amount__c = totalWithoutDiscount;
        if(isInventoryQtyAvailable){
            if (total > getTierMetadata.Auto_Approval_Limit__c) {
                order.Status__c = 'Manager Approval';
            } else {
                order.Status__c = 'Approved';
            }
        }
        else order.Status__c='On Hold';
        update order;
    }
    
    public static Boolean checkInventoryAvailability(String productId, Decimal quantity) {
        HttpRequest req = new HttpRequest();
    req.setEndpoint('callout:ExternalInventoryAPI/inventory/check?productId=' + productId + '&qty=' + quantity);
    req.setMethod('GET');

    Http http = new Http();
    HttpResponse res = http.send(req);

    if (res.getStatusCode() == 200) {
        // Parse the JSON response
        Map<String, Object> response = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
        if (response.containsKey('isAvailable')) {
            return (Boolean) response.get('isAvailable');
        }
    }
    return false;
    }
}