BraveBear/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orders</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BraveBear/force-app/main/default/objects/Order__c/fields/CustomerTier__c.field-meta.xml
<CustomField>
    <fullName>CustomerTier__c</fullName>
    <formula>Account__r.Tier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CustomerTier</label>
    <type>Text</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order__c/fields/Final_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Amount__c</fullName>
    <description>Final amount after discount</description>
    <label>Final Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Manager Approval</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BraveBear/force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total_Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/fields/Quantity_Available__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quantity Available</label>
    <type>Checkbox</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <formula>Products__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BraveBear/force-app/main/default/objects/Products__c/Products__c.object-meta.xml
<CustomObject>
    <label>Products</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BraveBear/force-app/main/default/objects/Products__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

BraveBear/force-app/main/default/classes/OrderProcessingBatch.cls
global class OrderProcessingBatch implements Database.Batchable<SObject>,Database.stateful, Database.AllowsCallouts {
    
    private List<Id> orderIds;
    List<Id> OrderIdsForApprovalProcess=new List<Id>();    
    public OrderProcessingBatch(List<Id> orderIds) {
        this.orderIds = orderIds;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Id, CustomerTier__c, Total_Amount__c, Discount__c, Final_Amount__c,note__c, Status__c
            FROM Order__c
            WHERE Id IN :orderIds
        ]);
    }
    
    global void execute(Database.BatchableContext BC, List<Order__c> orders) {
        // Query all Order Line Items for these orders
        Map<Id, List<Order_Line_Item__c>> orderLineItemsMap = new Map<Id, List<Order_Line_Item__c>>();
        List<Order_Line_Item__c> allLineItems = [
            SELECT Id, Quantity__c, Products__c, Products__r.ProductCode__c, Unit_Price__c,
            Discount__c, Final_Amount__c, Quantity_Available__c, API_Response__c, Order__c
            FROM Order_Line_Item__c
            WHERE Order__c IN :orderIds
        ];
        
        for (Order_Line_Item__c item : allLineItems) {
            if (!orderLineItemsMap.containsKey(item.Order__c)) {
                orderLineItemsMap.put(item.Order__c, new List<Order_Line_Item__c>());
            }
            orderLineItemsMap.get(item.Order__c).add(item);
        }
        List<Order_Line_Item__c> lineItemsToUpdate = new List<Order_Line_Item__c>();
        List<Order__c> ordersToUpdate = new List<Order__c>();
        
        for (Order__c order : orders) {
            String customerTierString = !String.isBlank(order.CustomerTier__c) ? order.CustomerTier__c : 'Standard';
            Customer_Tiers__mdt getTierMetadata = Customer_Tiers__mdt.getInstance(customerTierString);
            
            List<Order_Line_Item__c> lineItems = orderLineItemsMap.get(order.Id);
            
            Decimal total = 0;
            Decimal totalWithoutDiscount = 0;
            Boolean isInventoryQtyAvailable = true;
            
            if (lineItems != null) {
                for (Order_Line_Item__c item : lineItems) {
                    Decimal discount = getTierMetadata.Discount__c;
                    if (item.Quantity__c > 100) {
                        discount += 2;
                    }
                    Decimal price = item.Quantity__c * item.Unit_Price__c * (1 - discount / 100);
                    Decimal priceWithoutDiscount = item.Quantity__c * item.Unit_Price__c;
                    
                    item.Discount__c = discount;
                    item.Final_Amount__c = price;
                    
                    totalWithoutDiscount += priceWithoutDiscount;
                    total += price;
                    
                    try {
                        APIResponseWrapper isInventoryAvailable = checkInventoryAvailability(item.Products__r.ProductCode__c, item.Quantity__c);
                       	system.debug('isInventoryAvailable---------------------'+isInventoryAvailable);
                        item.Quantity_Available__c = isInventoryAvailable.isAvailable;
                        item.API_Response__c=isInventoryAvailable.responseBody;
                        if (!isInventoryAvailable.isAvailable) {
                            isInventoryQtyAvailable = false;
                        }
                    } catch (Exception ex) {
                        item.API_Response__c = ex.getMessage();
                        isInventoryQtyAvailable = false;
                    }
                    lineItemsToUpdate.add(item);
                }
            }
            
            order.Total_Amount__c = totalWithoutDiscount;
            order.Discount__c = !String.isBlank(order.CustomerTier__c) ? getTierMetadata.Discount__c : 0.0;
            order.Final_Amount__c = total; // final amount after discounts
            
            if (isInventoryQtyAvailable) {
                if (total > getTierMetadata.Auto_Approval_Limit__c) {
                    order.Status__c = 'Manager Approval';
                    order.Note__c='Waiting for managers approval';
                    OrderIdsForApprovalProcess.add(order.Id);                    
                } 
                else {
                    order.Status__c = 'Approved';
                }
            }
            else {
                order.Status__c = 'On Hold';
                order.note__c='Inventory is not available';
            }
            
            ordersToUpdate.add(order);
        }
        
        if (!lineItemsToUpdate.isEmpty()) {
            update lineItemsToUpdate;
        }
        
        if (!ordersToUpdate.isEmpty()) {
            update ordersToUpdate;
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        if (!OrderIdsForApprovalProcess.isEmpty()) {
            List<Order__c> orderToSubmitForApproval = [ SELECT Id FROM Order__c WHERE Id IN :OrderIdsForApprovalProcess    AND Status__c = 'Manager Approval'];
            
            for (Order__c order : orderToSubmitForApproval) {
                try {
                    Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                    req.setObjectId(order.Id);
                    Approval.process(req);
                } catch (Exception ex) {
                    System.debug('Error approving order ' + order.Id + ': ' + ex.getMessage());
                }
            }
        }
        
    }
    
    public static APIResponseWrapper checkInventoryAvailability(String productId, decimal quantity) {
     /*   HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:ExternalInventoryAPI/inventory/check?productId=' + productId + '&qty=' + quantity);
        req.setMethod('GET');
        
        Http http = new Http();
        HttpResponse res = http.send(req);
        APIResponseWrapper wrp=new APIResponseWrapper();
        wrp.responseBody=res.getBody();
        if (res.getStatusCode() == 200) {
            Map<String, Object> response = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            if (response.containsKey('isAvailable')) {
                wrp.isAvailable=true;
                
                //wrp.isAvailable=(Boolean)response.get('isAvailable');
                return wrp;
            }
        }
        else {
            //wrp.isAvailable=false;
            wrp.isAvailable=true;
        }*/
		APIResponseWrapper wrp=new APIResponseWrapper();  
        wrp.isAvailable=true;
        wrp.responseBody='{"productId":"P1001","requestedQty":10,"availableQty":5,"isAvailable":false}';
        return wrp;
    }
    public class APIResponseWrapper {
        public Boolean isAvailable;
        public String responseBody;
    }
}