BraveBear/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orders</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BraveBear/force-app/main/default/objects/Order__c/fields/Final_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Amount__c</fullName>
    <description>Final amount after discount</description>
    <label>Final Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Manager Approval</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

BraveBear/force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total_Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <referenceTo>Products__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

BraveBear/force-app/main/default/objects/Order_Line_Item__c/fields/Quantity_Available__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quantity Available</label>
    <type>Checkbox</type>
</CustomField>

BraveBear/force-app/main/default/objects/Products__c/Products__c.object-meta.xml
<CustomObject>
    <label>Products</label>
    <nameField>
        <label>Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BraveBear/force-app/main/default/objects/Products__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <externalId>true</externalId>
    <label>ProductCode</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

BraveBear/force-app/main/default/classes/OrderProcessingControllerTest.cls
@isTest
global class OrderProcessingControllerTest {
    
    @isTest static void testProcessWithInventoryAvailable() {
        // Setup test data
        Account acc = new Account(Name = 'Test Account', Tier__c = 'Gold');
        insert acc;
        
        Order__c order = new Order__c( Account__c = acc.Id);
        insert order;
        
        Products__c product = new Products__c(Name = 'Test Product', ProductCode__c = 'P1001',price__c=200);
        insert product;
        
        Order_Line_Item__c lineItem = new Order_Line_Item__c(
            Order__c = order.Id,
            Quantity__c = 10,
            Products__c = product.Id
        );
        insert lineItem;
        Test.setMock(HttpCalloutMock.class, new InventoryApiMock());
        Test.startTest();
        OMSQueueCallingController.processOrders(new List<Id> { order.Id });
        Test.stopTest();
        //OrderProcessingController.process(order);
       // Test.stopTest();
        
        order = [SELECT Status__c, Total_Amount__c, Discount__c, Final_Amount__c FROM Order__c WHERE Id = :order.Id];
        lineItem = [SELECT Discount__c, Final_Amount__c, Quantity_Available__c, API_Response__c FROM Order_Line_Item__c WHERE Id = :lineItem.Id];
        
        System.assertEquals('On Hold', order.Status__c, 'Order should be On Hold');
        System.assert(order.Total_Amount__c > 0, 'Total amount should be calculated');
        System.assert(lineItem.Quantity_Available__c == false, 'Quantity is not avaialble');
    }
 
    global class InventoryApiMock implements HttpCalloutMock {
        global HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            
            String body = '{"productId":"P1001","requestedQty":10,"availableQty":5,"isAvailable":false}';
            res.setBody(body);
            
            return res;
        }
    }
}